# Site settings
title: Philip Hendry's Blog
email: blog@philiphendry.me.uk
description: "Philip Hendry's Blog... one day there'll be enough time."
baseurl: ""
url: http://blog.philiphendry.me.uk
rss: http://blog.philiphendry.me.uk/feed.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
permalink: pretty
paginate: 10
paginate_path: "page/:num"

google_analytics_tracking_id: UA-51440511-1