# Site settings
title: Philip Hendry's Blog
email: blog@philiphendry.me.uk
description: "One day there'll be enough time."
baseurl: ""
url: http://blog.philiphendry.me.uk
rss: http://blog.philiphendry.me.uk/feed.xml


# Build settings
permalink: /:year/:month/:day/:title
paginate: 10
paginate_path: "page/:num"
markdown: redcarpet
redcarpet:
    extensions: ["tables"]

google_analytics_tracking_id: UA-51440511-1